#!/bin/sh
# chkconfig: 345 99 0
# description: 1C administration cluster server
# processname: Ras-server


# Source function library
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 0
fi
KIND="Ras1CServer"
RAS_SERVER=/opt/1C/v8.3/x86_64/ras
start() {
        echo -n $"Starting $KIND daemon: "
        daemon $RAS_SERVER cluster --daemon &
        echo
}

stop() {
        echo -n $"Shutting down $KIND daemon: "
        killproc  $RAS_SERVER
        echo
}

restart() {
            echo -n $"Restarting $KIND daemon: "
           stop
           start
           echo
}

case "$1" in
  start)
          start
        ;;
  stop)
          stop
        ;;
  restart)
          restart
        ;;
  status)
    status idServer
    ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
exit $?
